-- Tablas canónicas de staging del Oracle Geocoder.
-- Las tablas STG_CARTO_*, STG_OSM_* y STG_RT_* las crea ogr2ogr porque
-- sus columnas dependen de la edición concreta de cada fuente.

BEGIN
  FOR t IN (
    SELECT table_name FROM user_tables
    WHERE table_name IN (
      'STG_GC_ADDRESS_POINT_ES', 'STG_GC_ROAD_ES', 'STG_GC_ROAD_SEGMENT_ES',
      'STG_GC_AREA_ES', 'STG_GC_POSTAL_CODE_ES', 'STG_GC_POI_ES'
    )
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' PURGE';
  END LOOP;
END;
/

CREATE TABLE STG_GC_ADDRESS_POINT_ES (
  SOURCE_ID VARCHAR2(100) NOT NULL, SOURCE_NAME VARCHAR2(30) NOT NULL,
  STREET_TYPE VARCHAR2(30), STREET_NAME VARCHAR2(200), HOUSE_NUMBER VARCHAR2(30),
  UNIT VARCHAR2(50), PLACE_ID VARCHAR2(30), PLACE_NAME VARCHAR2(200),
  POSTAL_CODE VARCHAR2(5), MUNICIPALITY_CODE VARCHAR2(5),
  MUNICIPALITY_NAME VARCHAR2(128), PROVINCE_NAME VARCHAR2(50),
  REGION_NAME VARCHAR2(50), SOURCE_DATE TIMESTAMP, GEOM SDO_GEOMETRY
);

CREATE TABLE STG_GC_ROAD_ES (
  SOURCE_ID VARCHAR2(100) NOT NULL, SOURCE_NAME VARCHAR2(30) NOT NULL,
  STREET_TYPE VARCHAR2(30), NAME VARCHAR2(200), REF VARCHAR2(50),
  ONE_WAY VARCHAR2(1), CLASS_NAME VARCHAR2(50), GEOM SDO_GEOMETRY
);

CREATE TABLE STG_GC_ROAD_SEGMENT_ES (
  SOURCE_ID VARCHAR2(100) NOT NULL, SOURCE_NAME VARCHAR2(30) NOT NULL,
  ROAD_SOURCE_ID VARCHAR2(100), LEFT_FROM VARCHAR2(30), LEFT_TO VARCHAR2(30),
  RIGHT_FROM VARCHAR2(30), RIGHT_TO VARCHAR2(30), GEOM SDO_GEOMETRY
);

CREATE TABLE STG_GC_AREA_ES (
  SOURCE_ID VARCHAR2(100) NOT NULL, SOURCE_NAME VARCHAR2(30) NOT NULL,
  AREA_TYPE VARCHAR2(30), NAME VARCHAR2(200), PARENT_SOURCE_ID VARCHAR2(100),
  GEOM SDO_GEOMETRY
);

CREATE TABLE STG_GC_POSTAL_CODE_ES (
  POSTAL_CODE VARCHAR2(5) NOT NULL, MUNICIPALITY_CODE VARCHAR2(5),
  MUNICIPALITY_NAME VARCHAR2(128), SOURCE_NAME VARCHAR2(30) NOT NULL
);

CREATE TABLE STG_GC_POI_ES (
  SOURCE_ID VARCHAR2(100) NOT NULL, SOURCE_NAME VARCHAR2(30) NOT NULL,
  NAME VARCHAR2(200), CLASS_NAME VARCHAR2(50), GEOM SDO_GEOMETRY
);
