-- Índices espaciales para las tablas canónicas de staging.

CREATE INDEX STG_GC_ADDRESS_POINT_ES_SX ON STG_GC_ADDRESS_POINT_ES(GEOM)
  INDEXTYPE IS MDSYS.SPATIAL_INDEX;
CREATE INDEX STG_GC_ROAD_ES_SX ON STG_GC_ROAD_ES(GEOM)
  INDEXTYPE IS MDSYS.SPATIAL_INDEX;
CREATE INDEX STG_GC_ROAD_SEGMENT_ES_SX ON STG_GC_ROAD_SEGMENT_ES(GEOM)
  INDEXTYPE IS MDSYS.SPATIAL_INDEX;
CREATE INDEX STG_GC_AREA_ES_SX ON STG_GC_AREA_ES(GEOM)
  INDEXTYPE IS MDSYS.SPATIAL_INDEX;
CREATE INDEX STG_GC_POI_ES_SX ON STG_GC_POI_ES(GEOM)
  INDEXTYPE IS MDSYS.SPATIAL_INDEX;
