-- Staging independiente del esquema oficial Oracle Geocoder.
-- Ejecutar con el usuario propietario de las tablas de staging.

BEGIN
  FOR t IN (
    SELECT table_name FROM user_tables
    WHERE table_name IN (
      'STG_GC_ADDRESS_POINT_ES', 'STG_GC_ROAD_ES', 'STG_GC_ROAD_SEGMENT_ES',
      'STG_GC_AREA_ES', 'STG_GC_POSTAL_CODE_ES', 'STG_GC_POI_ES'
    )
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' PURGE';
  END LOOP;
END;
/

CREATE TABLE STG_GC_ADDRESS_POINT_ES (
  SOURCE_ID VARCHAR2(100) NOT NULL, SOURCE_NAME VARCHAR2(30) NOT NULL,
  STREET_TYPE VARCHAR2(30), STREET_NAME VARCHAR2(200), HOUSE_NUMBER VARCHAR2(30),
  UNIT VARCHAR2(50), PLACE_ID VARCHAR2(30), PLACE_NAME VARCHAR2(200),
  POSTAL_CODE VARCHAR2(5), MUNICIPALITY_CODE VARCHAR2(5),
  MUNICIPALITY_NAME VARCHAR2(128), PROVINCE_NAME VARCHAR2(50),
  REGION_NAME VARCHAR2(50), SOURCE_DATE TIMESTAMP, GEOM SDO_GEOMETRY
);

CREATE TABLE STG_GC_ROAD_ES (
  SOURCE_ID VARCHAR2(100) NOT NULL, SOURCE_NAME VARCHAR2(30) NOT NULL,
  STREET_TYPE VARCHAR2(30), NAME VARCHAR2(200), REF VARCHAR2(50),
  ONE_WAY VARCHAR2(1), CLASS_NAME VARCHAR2(50), GEOM SDO_GEOMETRY
);

CREATE TABLE STG_GC_ROAD_SEGMENT_ES (
  SOURCE_ID VARCHAR2(100) NOT NULL, SOURCE_NAME VARCHAR2(30) NOT NULL,
  ROAD_SOURCE_ID VARCHAR2(100), LEFT_FROM VARCHAR2(30), LEFT_TO VARCHAR2(30),
  RIGHT_FROM VARCHAR2(30), RIGHT_TO VARCHAR2(30), GEOM SDO_GEOMETRY
);

CREATE TABLE STG_GC_AREA_ES (
  SOURCE_ID VARCHAR2(100) NOT NULL, SOURCE_NAME VARCHAR2(30) NOT NULL,
  AREA_TYPE VARCHAR2(30), NAME VARCHAR2(200), PARENT_SOURCE_ID VARCHAR2(100),
  GEOM SDO_GEOMETRY
);

CREATE TABLE STG_GC_POSTAL_CODE_ES (
  POSTAL_CODE VARCHAR2(5) NOT NULL, MUNICIPALITY_CODE VARCHAR2(5),
  MUNICIPALITY_NAME VARCHAR2(128), SOURCE_NAME VARCHAR2(30) NOT NULL
);

CREATE TABLE STG_GC_POI_ES (
  SOURCE_ID VARCHAR2(100) NOT NULL, SOURCE_NAME VARCHAR2(30) NOT NULL,
  NAME VARCHAR2(200), CLASS_NAME VARCHAR2(50), GEOM SDO_GEOMETRY
);

BEGIN
  FOR r IN (
    SELECT table_name, column_name
    FROM user_sdo_geom_metadata
    WHERE table_name IN (
      'STG_GC_ADDRESS_POINT_ES', 'STG_GC_ROAD_ES',
      'STG_GC_ROAD_SEGMENT_ES', 'STG_GC_AREA_ES', 'STG_GC_POI_ES'
    )
  ) LOOP
    DELETE FROM user_sdo_geom_metadata
    WHERE table_name = r.table_name AND column_name = r.column_name;
  END LOOP;
END;
/

INSERT ALL
  INTO user_sdo_geom_metadata VALUES
    ('STG_GC_ADDRESS_POINT_ES', 'GEOM',
     MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X', -180, 180, 0.000001),
                         MDSYS.SDO_DIM_ELEMENT('Y', -90, 90, 0.000001)), 4258)
  INTO user_sdo_geom_metadata VALUES
    ('STG_GC_ROAD_ES', 'GEOM',
     MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X', -180, 180, 0.000001),
                         MDSYS.SDO_DIM_ELEMENT('Y', -90, 90, 0.000001)), 4258)
  INTO user_sdo_geom_metadata VALUES
    ('STG_GC_ROAD_SEGMENT_ES', 'GEOM',
     MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X', -180, 180, 0.000001),
                         MDSYS.SDO_DIM_ELEMENT('Y', -90, 90, 0.000001)), 4258)
  INTO user_sdo_geom_metadata VALUES
    ('STG_GC_AREA_ES', 'GEOM',
     MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X', -180, 180, 0.000001),
                         MDSYS.SDO_DIM_ELEMENT('Y', -90, 90, 0.000001)), 4258)
  INTO user_sdo_geom_metadata VALUES
    ('STG_GC_POI_ES', 'GEOM',
     MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X', -180, 180, 0.000001),
                         MDSYS.SDO_DIM_ELEMENT('Y', -90, 90, 0.000001)), 4258)
SELECT 1 FROM dual;

CREATE INDEX STG_GC_ADDRESS_POINT_ES_SX ON STG_GC_ADDRESS_POINT_ES(GEOM)
  INDEXTYPE IS MDSYS.SPATIAL_INDEX;
CREATE INDEX STG_GC_ROAD_ES_SX ON STG_GC_ROAD_ES(GEOM)
  INDEXTYPE IS MDSYS.SPATIAL_INDEX;
CREATE INDEX STG_GC_ROAD_SEGMENT_ES_SX ON STG_GC_ROAD_SEGMENT_ES(GEOM)
  INDEXTYPE IS MDSYS.SPATIAL_INDEX;
CREATE INDEX STG_GC_AREA_ES_SX ON STG_GC_AREA_ES(GEOM)
  INDEXTYPE IS MDSYS.SPATIAL_INDEX;
CREATE INDEX STG_GC_POI_ES_SX ON STG_GC_POI_ES(GEOM)
  INDEXTYPE IS MDSYS.SPATIAL_INDEX;
