-- Controles previos a cualquier carga en tablas oficiales GC_*_ES.

SELECT 'ADDRESS_POINTS' AS OBJECT_NAME, COUNT(*) AS ROW_COUNT
FROM STG_GC_ADDRESS_POINT_ES
UNION ALL
SELECT 'ROADS', COUNT(*) FROM STG_GC_ROAD_ES
UNION ALL
SELECT 'AREAS', COUNT(*) FROM STG_GC_AREA_ES
UNION ALL
SELECT 'POSTAL_CODES', COUNT(*) FROM STG_GC_POSTAL_CODE_ES
UNION ALL
SELECT 'POI', COUNT(*) FROM STG_GC_POI_ES;

SELECT 'PORTALS_WITHOUT_POSTAL_CODE' AS CHECK_NAME, COUNT(*) AS FAIL_COUNT
FROM STG_GC_ADDRESS_POINT_ES
WHERE POSTAL_CODE IS NULL
UNION ALL
SELECT 'PORTALS_WITHOUT_MUNICIPALITY', COUNT(*)
FROM STG_GC_ADDRESS_POINT_ES
WHERE MUNICIPALITY_NAME IS NULL
UNION ALL
SELECT 'PORTALS_WITHOUT_GEOMETRY', COUNT(*)
FROM STG_GC_ADDRESS_POINT_ES
WHERE GEOM IS NULL
UNION ALL
SELECT 'DUPLICATE_PORTAL_SOURCE_IDS', COUNT(*)
FROM (
  SELECT SOURCE_ID FROM STG_GC_ADDRESS_POINT_ES
  GROUP BY SOURCE_ID HAVING COUNT(*) > 1
);
